[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "impeller"
version = "0.0.0"
description = "Analyze and build lake projects"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pygithub>=2.9.1",
]

[project.scripts]
impeller-analyze = "impeller.analyze:main"
impeller-build = "impeller.build:main"

[tool.ruff.format]
preview = true
